### ISSUE TITLE
[SUGGESTION] Improve heath checks when a mtls policy is applied

### ISSUE THREAD

**Issue by saberkan** [lbroudoux/cheese-quizz#6]
This is a suggestion to improve mtls part.

**DESCRIPTION**:
When applying mtls in destination rule, it is recommended to apply a policy in order to insure the traffic encryption in a strict way. 
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: "default"
  namespace: "microservices-demo"
spec:
  peers:
  - mtls:
      mode: STRICT

```

Meanwhile, when applying this policy all the system goes down. Pod go into CrashLoopBack status because liveness and readiness probes are rejected.

**EXCPECTED**:
- Add in the lab a tep to apply the policy
- Fix liveness and readiness probes to support the policy

**HOW TO IMPROVE**:
Change all the liveness and the readiness probes to use localhost check with curl (best practice), rather than httpGet which uses pod IP (and blocked by peer when a policy is applied).
```
exec:
  command:
  - curl
  - -f
  - http://localhost:8080/healthz # Replace port and URI by your actual health check
```

Source: https://istio.io/latest/faq/security/#k8s-health-checks
